[features]
seeds = false
skip-lint = false

[programs.localnet]
educore_contracts = "EduCore11111111111111111111111111111111111111111111"

[programs.devnet]
educore_contracts = "EduCore11111111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
